export const categories = [
  // 🐾 Animals & Nature
  "Animals",
  "Birds",
  "Fish",
  "Insects",
  "Reptiles",
  "Pets",
  "Farm Animals",
  "Wild Animals",
  "Ocean Creatures",
  "Plants",
  "Trees",
  "Flowers",
  "Fruits",
  "Vegetables",
  "Rocks and Minerals",
  "Natural Landforms",
  "Weather",
  "Habitats",
  "Biomes",

  // 🥐 Food & Drink
  "Foods",
  "Snacks",
  "Desserts",
  "Beverages",
  "Breakfast Foods",
  "Fast Food Items",
  "Fruits and Vegetables",
  "Dishes from Around the World",
  "Spices and Herbs",
  "Baked Goods",

  // 🏀 Sports & Hobbies
  "Sports",
  "Outdoor Activities",
  "Board Games",
  "Card Games",
  "Video Games",
  "Hobbies",
  "Instruments",
  "Dance Styles",
  "Martial Arts",
  "Olympic Sports",

  // 🎬 Entertainment
  "Movies",
  "TV Shows",
  "Cartoon Characters",
  "Anime Characters",
  "YouTube Channels",
  "Streamers",
  "Famous People",
  "Comedians",
  "Singers",
  "Bands",
  "Rappers",
  "Superheroes",
  "Supervillains",
  "Book Titles",
  "Authors",
  "Fairy Tales",
  "Mythical Creatures",
  "Board Game Characters",

  // 🧠 Knowledge & Education
  "School Subjects",
  "Languages",
  "Math Terms",
  "Science Terms",
  "Geography Terms",
  "Historical Figures",
  "Inventions",
  "Planets",
  "Elements",
  "Technology",
  "Computer Parts",
  "Jobs",
  "Tools",
  "Vehicles",
  "Weapons from History (non-violent context)",
  "Ancient Civilizations",
  "Mythologies",
  "Space Objects",

  // 🏙️ Places & Geography
  "Countries",
  "Cities",
  "Continents",
  "Mountains",
  "Oceans",
  "Rivers",
  "Famous Landmarks",
  "Buildings",
  "Transportation",
  "Vacation Spots",
  "Capital Cities",

  // 👕 Everyday Objects
  "Clothing",
  "Shoes",
  "Accessories",
  "Furniture",
  "Kitchen Items",
  "Bathroom Items",
  "Office Supplies",
  "Tools",
  "Toys",
  "School Supplies",
  "Electronics",
  "Household Items",
  "Musical Instruments",

  // 🎨 Creative & Fun
  "Colors",
  "Shapes",
  "Patterns",
  "Emotions",
  "Art Styles",
  "Dance Moves",
  "Craft Materials",
  "Holidays",
  "Decorations",
  "Toys from the 2000s",
  "Trends",
  "Internet Memes",
  "Fantasy Worlds",
  "Magic Spells",
  "Superpowers",

  // ⏳ Time & History
  "Historical Events",
  "Decades",
  "Eras",
  "Famous Leaders",
  "Ancient Myths",
  "Dinosaurs",
  "Old Technologies",

  // 👤 People & Culture
  "Occupations",
  "Professions",
  "Famous Artists",
  "Inventors",
  "Royalty",
  "Philosophers",
  "Explorers",
  "Actors",
  "Athletes",
  "Scientists",

  // 🌍 Miscellaneous / Catch-All
  "Random Objects",
  "Funny Words",
  "Fantasy Items",
  "Video Game Items",
  "Pop Culture References",
  "App Names",
  "Board Games",
  "School Life",
  "Camping Gear",
  "Musical Genres",
  "Transportation Types",
  "Climates",
  "Materials",
  "Textures",
  "Sounds",
  "Feelings",
  "Languages of the World",
  "Animals from Movies",
  "Cartoon Locations",
  "Popular Apps",
  "Toys from Movies"
];
