export default [
  // 🐾 Animals & Nature
  "Animals (General)",
  "Birds (Non-Specific)",
  "Fish (Non-Specific)",
  "Insects (Common)",
  "Reptiles (Common)",
  "Pets (Common)",
  "Farm Animals (Common)",
  "Plants (General)",
  "Trees (Common)",
  "Flowers (Common)",
  "Fruits (Common)",
  "Vegetables (Common)",
  "Rocks and Minerals (Common)",
  "Natural Landforms (Factual)",
  "Weather Phenomena (Factual)",
  "Habitats (Factual)",

  // 🥐 Food & Drink
  "Foods (General)",
  "Snacks (General)",
  "Desserts (General)",
  "Beverages (General)",
  "Breakfast Foods (General)",
  "Baked Goods (General)",
  "Ingredients (General)",
  "Spices and Herbs (General)",

  // 🏀 Sports & Hobbies
  "Sports (Major)",
  "Outdoor Activities (Common)",
  "Board Games (Classic)",
  "Card Games (Classic)",
  "Hobbies (Common)",
  "Instruments (Common)",
  "Dance Styles (Formal)",
  "Olympic Sports (Factual)",

  // 🎬 Entertainment - **Focus on Factual/Educational**
  "General Film Genres",
  "General Television Formats",
  "Book Genres",
  "Classic Literature Titles",
  "Mythological Figures (Non-Graphic)",
  "Fairy Tale Characters (Classic)",
  "Super Powers (Fictional, Non-Violent)",

  // 🧠 Knowledge & Education
  "School Subjects (Factual)",
  "Languages (Common)",
  "Math Terms (Factual)",
  "Science Terms (Factual)",
  "Geography Terms (Factual)",
  "Inventions (Factual)",
  "Planets and Stars (Factual)",
  "Elements (Chemical)",
  "Technology (General Concepts)",
  "Computer Parts (Factual)",
  "Jobs (Common)",
  "Tools (Common)",
  "Vehicles (Common)",
  "Ancient Civilizations (Factual)",
  "Space Objects (Factual)",

  // 🏙️ Places & Geography
  "Countries (Current)",
  "Cities (Major)",
  "Continents (Factual)",
  "Mountains (Factual)",
  "Oceans and Seas (Factual)",
  "Rivers (Factual)",
  "Famous Landmarks (Factual)",
  "Buildings (General Types)",
  "Transportation Methods",
  "Capital Cities (Factual)",

  // 👕 Everyday Objects
  "Clothing (General)",
  "Shoes (General)",
  "Accessories (General)",
  "Furniture (General)",
  "Kitchen Items (Common)",
  "Bathroom Items (Common)",
  "Office Supplies (Common)",
  "Toys (Classic)",
  "School Supplies (Common)",
  "Electronics (General)",
  "Household Items (General)",

  // 🎨 Creative & Fun
  "Colors (Basic)",
  "Shapes (Geometric)",
  "Patterns (General)",
  "Emotions (Basic)",
  "Art Styles (Historical)",
  "Craft Materials (Common)",
  "Holidays (Major)",
  "Decorations (General)",
  "Fantasy Worlds (Generic Concepts)",

  // ⏳ Time & History
  "Historical Eras (Broad)",
  "Decades (Factual)",
  "Dinosaurs (Factual)",
  "Old Technologies (Factual)",

  // 👤 People & Culture - **Focus on Neutral Titles**
  "Occupations (General)",
  "Professions (General)",
  "Roles in Government",
  "Scientific Fields",
  "Exploration Topics",
  "Philosophical Concepts",
];